runtime: python
env: flex

runtime_config:
    python_version: 3

env_variables:
  SERVER_ENV: "production"

entrypoint:
  gunicorn --bind 0.0.0.0:8080 app:app

beta_settings:
  cloud_sql_instances: cs348-database10:us-central1:cs348demo-db

manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10